spring:
  application:
    name: backend

  datasource:
    url: jdbc:postgresql://localhost:5432/assistant_db?options=-c%20timezone=Asia/Kolkata
    username: assistant_user
    password: assistant_pass
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - email
              - profile
jwt:
  secret: ${JWT_SECRET}
  expiration-ms: 86400000
server:
  port: 8080